function P = idt_default_params()
% IDT_DEFAULT_PARAMS  Complete default parameter set of the simulation model.
%
%   P = idt_default_params()
%
% You normally do NOT edit this file. The simulation scripts (SIM_*.m) list every parameter explicitly
% (same names) so students can see and change them in one place. This function only
% fills in fields that a script or an older params file leaves out.
%
% The defaults describe the example assembly shipped in cad/ (holder + design frame + fixed frame).
% Full parameter documentation: docs/01_model_setup.md
%
% UNITS: meters, kilograms, newtons, seconds, Hz.
%
% Author: Dr. Osman Sayginer (InverseDesignToolbox)

    %% 1. GEOMETRY
    P.Geometry.Files     = {'cad/03AccHolder.STEP', 'cad/02DesignFrame.STEP', 'cad/01FixedFrame.STEP'};
    P.Geometry.Names     = {'Holder', 'Design frame', 'Fixed frame'};
    P.Geometry.Materials = {struct('Name', 'TPU-Heavy', 'E', 0.05e9, 'nu', 0.45, 'rho', 2000), ...
                            struct('Name', 'TPU',       'E', 0.05e9, 'nu', 0.45, 'rho', 1200), ...
                            struct('Name', 'TPU',       'E', 0.05e9, 'nu', 0.45, 'rho', 1200)};
    P.Geometry.Scale     = 1;

    %% 2. DESIGN DOMAIN (the part of the geometry an optimizer may change)
    P.Design.Type         = 'bricks';   % 'bricks' | 'none' (analysis of the geometry exactly as imported)
    P.Design.Part         = 2;          % bricks: which part is the design domain
    P.Design.MinPrintSize = 1.0e-3;     % bricks: smallest printable feature [m]
    P.Design.Density      = 30;         % bricks: 0 (coarse) ... 100 (finest)
    P.Design.Layers       = [0 0 3];    % bricks: hard layer counts [nx ny nz], 0 = automatic
    P.Design.MinFill      = 0.5;        % bricks: a cell must be at least this full of design material
    P.Design.MaxOverlap   = 0;          % bricks: ... and overlap other parts by at most this fraction

    %% 3. BOUNDARY CONDITIONS
    P.BC.FixedFaces     = [1 2 3 4];
    P.BC.LoadPoint      = [0 0 5e-3];
    P.BC.LoadDirection  = [0 0 1];
    P.BC.LoadAmplitude  = 1.0;
    P.BC.OutPoints      = [0 0 5e-3; 8.67e-3 6.76e-3 5e-3];
    P.BC.ExtraMass      = 0.005;
    P.BC.ExtraMassBox   = [-10.25e-3 10.25e-3 -8e-3 8e-3 -Inf Inf];

    %% 4. MESH
    P.Mesh.Hmax   = 2.0e-3;
    P.Mesh.Order  = 'linear';
    P.Mesh.Refine = {};

    %% 5. ANALYSIS
    P.Analysis.Type              = 'ModalHarmonic';   % eigenfrequencies + harmonic response
    P.Analysis.FreqStart         = 2;
    P.Analysis.FreqEnd           = 300;
    P.Analysis.FreqStep          = 3;
    P.Analysis.Zeta              = 0.05;
    P.Analysis.NModes            = 8;
    P.Analysis.Transmissibility  = true;              % also compute base-excitation transmissibility
end
